//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int id { get; set; }
        public System.DateTime deadendDate { get; set; }
        public Nullable<System.DateTime> datePayed { get; set; }
        public decimal total { get; set; }
        public bool isPayed { get; set; }
        public int idStudent { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
