//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string ssn { get; set; }
        public bool isExmatriculated { get; set; }
        public int idCampus { get; set; }
        public Nullable<int> idRoom { get; set; }
        public int idType { get; set; }
        public int idUni { get; set; }
    
        public virtual Campu Campu { get; set; }
        public virtual CampusRoom CampusRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual StudentType StudentType { get; set; }
        public virtual University University { get; set; }
    }
}
